### ISSUE TITLE
A bit correlated - typo

### ISSUE THREAD

**Issue by korbinian90** [tpolakovic/tpolakovic.github.io#1]
In the 0th post, the second Hamiltonian equation:
dq/dt = dH/d**q**
=>
dq/dt = dH/d**p**

PS: Until now, I really enjoy it and I'm excited to keep on reading and testing out code myself!

**Comment by korbinian90** [comment]
And I found slightly below the link for operators on Wikipedia to be broken.
The trailing ")" appears in text instead of the link (chrome on Android)

**Comment by tpolakovic** [comment]
Thanks for pointing that out.

Pelican does some weird stuff, so the trailing parens don't show as a problem when I write the source Jupyter notebooks. Both links and the typo should be fixed in dd478faec5e353289817f972a2d6ab0b8c6943b4
